resources:
 # - url: !resource fold-entity-row/fold-entity-row.js
 #   type: js
 # - url: !resource animated-weather-card/weather-card.js
 #   type: js
 # - url: !resource layout-card/layout-card.js
 #   type: js
 # - url: !resource popup-card/popup-card.js
 #   type: js
 # - url: !resource light-card/light-card.js
 #   type: js
 # - url: !resource card-modder/card-modder.js
 #   type: js
 # - url: https://unpkg.com/moment@2.22.2/moment.js
 #   type: js
 # - url: !resource calendar/calendar-card.js
 #   type: module
 # - url: !resource dual-gauge/dual-gauge-card.js
 #   type: js
 # - url: !resource kiosk/kiosk.js
 #   type: js
 # - url: !resource button-card/button-card.js
 #   type: module
 # - url: !resource slider-entity-row/slider-entity-row.js
 #   type: js
 # - url: !resource useful-markdown-card/useful-markdown-card.js
 #   type: js
 # - url: !resource column-card/column-card.js
 #   type: js
 # - url: !resource tracker-card/tracker-card.js?v=0.3.0
 #   type: js
 # - url: !resource light-slider/light-slider-element.js
 #   type: js
 # - url: !resource state-element/state-element.js
 #   type: js
 # - url: !resource username-element/username-element.js
 #   type: js
 # - url: !resource state-attribute-element/state-attribute-element.js
 #   type: js
 # - url: !resource mini-media-player/mini-media-player.js?v=0.5
 #   type: module
 # - url: !resource toggle-lock-entity-row/toggle-lock-entity-row.js
 #   type: js

  # custom-lovelace
  - url: /local/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js?v=0.4.0
    type: js  
  - url: /local/custom-lovelace/beer-card/beer-card.js?v=0.2.3
    type: js  
  - url: /local/custom-lovelace/bignumber-card/bignumber-card.js?v=0.0.1
    type: js  
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js?v=0.1.1
    type: js  
  - url: /local/custom-lovelace/gauge-card/gauge-card.js?v=0.2.0
    type: js  
  - url: /local/custom-lovelace/group-card/group-card.js?v=0.0.2
    type: js  
  - url: /local/custom-lovelace/home-setter/home-setter.js?v=0.0.1
    type: js  
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=0.2.3
    type: js  
  - url: /local/custom-lovelace/plan-coordinates/plan-coordinates.js?v=0.1.0
    type: js  
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=0.1.1
    type: js 
  # tracker-card 
  - url: /local/tracker-card.js?v=0
    type: js
  # other
  - url: /local/text-element.js?v=0.0.2
    type: js
  - url: /local/circle-sensor-card.js?v=1.2.0
    type: module
  - url: /local/vertical-stack-in-card.js?v=0.1.0
    type: js
  - url: /local/krisinfo-card.js?v=0.0.4
    type: js
  - url: /local/button-card.js?v=0
    type: module
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css 
    
title: Home
# excluded_entities:
#   {% for state in states.alert %}
#   - {{ states.alert[state].entity_id }}
#   {% endfor %}
#   {% for state in states.automation %}
#   - {{ states.automation[state].entity_id }}
#   {% endfor %}
#   {% for state in states.zwave %}
#   - {{ states.zwave[state].entity_id }}
#   {% endfor %}
views:
  - !include 00_home_view.yaml
  - !include 10_downstairs_view.yaml
  - !include 20_upstairs_view.yaml
  - !include 30_basement_view.yaml
  - !include 40_car_view.yaml
  - !include 50_finance_view.yaml
  - !include 60_pool_view.yaml
  - !include 99_system_view.yaml
