title: Home

resources:
  # custom-lovelace
  - url: /local/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js
    type: js  
  - url: /local/custom-lovelace/bignumber-card/bignumber-card.js
    type: js  
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js
    type: js  
  - url: /local/custom-lovelace/gauge-card/gauge-card.js
    type: js  
  - url: /local/custom-lovelace/group-card/group-card.js
    type: js  
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js
    type: js 

  # other
  - url: /local/card-tools.js
    type: js
  - url: /local/pollenkoll-card.js
    type: js

  # community
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
    type: module
  - url: /community_plugin/krisinfo-card/krisinfo-card.js
    type: js
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
    
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.8/dist/spotify-card.umd.js
      
  # other
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css 
    
views:
  - !include 00_home_view.yaml
  - !include 09_lights_view.yaml
  #- !include 10_downstairs_view.yaml
  - !include 19_thermostats_view.yaml
  #- !include 20_upstairs_view.yaml
  #- !include 30_basement_view.yaml
  - !include 40_car_view.yaml
  - !include 50_finance_view.yaml
  - !include 60_pool_view.yaml
  - !include 99_system_view.yaml
