title: Home

custom_header:
  compact_mode: true

resources:
  # custom-lovelace
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js
    type: js  
  - url: /local/custom-lovelace/group-card/group-card.js
    type: js  

  # other
  - url: /local/card-tools.js
    type: js
  - url: /local/pollenkoll-card.js
    type: js

  # community
  - url: /hacsfiles/banner-card/banner-card.js  # /community_plugin/banner-card/banner-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/button-toolbar/button-toolbar.js
    type: module
  - url: /hacsfiles/calendar-card/calendar-card.js
    type: js
  - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/dual-gauge-card/dual-gauge-card.js
    type: js
  - url: /hacsfiles/krisinfo-card/krisinfo-card.js
    type: js
  - url: /hacsfiles/light-brightness-preset-row/light-brightness-preset-row.js
    type: js
  - url: /hacsfiles/list-card/list-card.js
    type: js
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js   # /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: >-
      https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.8/dist/spotify-card.umd.js
    type: module
  - url: /hacsfiles/text-element/text-element.js
    type: js
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    type: module

  # other
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css 
    
views:
  - !include 00_home_view.yaml
  - !include 09_lights_view.yaml
  #- !include 10_downstairs_view.yaml
  - !include 19_thermostats_view.yaml
  #- !include 20_upstairs_view.yaml
  #- !include 30_basement_view.yaml
  - !include 40_car_view.yaml
  - !include 45_security_view.yaml
  - !include 50_finance_view.yaml
  - !include 60_pool_view.yaml
  - !include 70_health_view.yaml
  - !include 80_washer_view.yaml
  - !include 99_system_view.yaml
