resources:
 # - url: !resource plan-coordinates/plan-coordinates.js
 #   type: js
 # - url: !resource fold-entity-row/fold-entity-row.js
 #   type: js
 # - url: !resource animated-weather-card/weather-card.js
 #   type: js
 # - url: !resource monster-card/monster-card.js?v=0.2.3
 #   type: js
 # - url: !resource layout-card/layout-card.js
 #   type: js
 # - url: !resource popup-card/popup-card.js
 #   type: js
 # - url: !resource light-card/light-card.js
 #   type: js
 # - url: !resource card-modder/card-modder.js
 #   type: js
 # - url: https://unpkg.com/moment@2.22.2/moment.js
 #   type: js
 # - url: !resource calendar/calendar-card.js
 #   type: module
 # - url: !resource dual-gauge/dual-gauge-card.js
 #   type: js
 # - url: !resource kiosk/kiosk.js
 #   type: js
 # - url: !resource button-card/button-card.js
 #   type: module
 # - url: !resource vertical-stack-in-card/vertical-stack-in-card.js?v=0.0.8
 #   type: js
 # - url: !resource slider-entity-row/slider-entity-row.js
 #   type: js
 # - url: !resource useful-markdown-card/useful-markdown-card.js
 #   type: js
 # - url: !resource gauge-card/gauge-card.js
 #   type: js
 # - url: !resource bignumber/bignumber-card.js
 #   type: js
 # - url: !resource column-card/column-card.js
 #   type: js
 # - url: !resource alarm_control_panel-card/alarm_control_panel-card.js
 #   type: js
 # - url: !resource entity-attributes-card/entity-attributes-card.js?v=0.1.1
 #   type: js
 # - url: !resource home-setter/home-setter.js?v=0.0.1
 #   type: js
 # - url: !resource tracker-card/tracker-card.js?v=0.1.5
 #   type: js
 # - url: !resource light-slider/light-slider-element.js
 #   type: js
 # - url: !resource group-card/group-card.js
 #   type: js
 # - url: !resource state-element/state-element.js
 #   type: js
 # - url: !resource text-element/text-element.js
 #   type: js
 # - url: !resource username-element/username-element.js
 #   type: js
 # - url: !resource state-attribute-element/state-attribute-element.js
 #   type: js
 # - url: !resource mini-media-player/mini-media-player.js?v=0.5
 #   type: module
 # - url: !resource toggle-lock-entity-row/toggle-lock-entity-row.js
 #   type: js

  - url: /local/krisinfo-card.js
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css 

title: Home
# excluded_entities:
#   {% for state in states.alert %}
#   - {{ states.alert[state].entity_id }}
#   {% endfor %}
#   {% for state in states.automation %}
#   - {{ states.automation[state].entity_id }}
#   {% endfor %}
#   {% for state in states.zwave %}
#   - {{ states.zwave[state].entity_id }}
#   {% endfor %}
views:
  - !include 00_home_view.yaml
  - !include 10_downstairs_view.yaml
  - !include 20_upstairs_view.yaml
  - !include 30_basement_view.yaml
#  - !include 00_home_view.yaml
#  - !include 10_home_info_view.yaml
#  - !include 20_lights_view.yaml
#  - !include 30_system_info_view.yaml
#  - !include 40_camera_view.yaml
#  - !include 50_cat_view.yaml
  # - !include 60_floorplan_view.yaml
#  - !include 70_isa_view.yaml
#  - !include 80_automations_view.yaml
#  - !include 100_settings_view.yaml
#  - !include 101_dashboard.yaml
#  - !include 102_alarm_clock.yaml
#  - !include 103_dashboard_test.yaml