resources:
 # - url: !resource fold-entity-row/fold-entity-row.js
 #   type: js
 # - url: !resource animated-weather-card/weather-card.js
 #   type: js
 # - url: !resource layout-card/layout-card.js
 #   type: js
 # - url: !resource popup-card/popup-card.js
 #   type: js
 # - url: !resource light-card/light-card.js
 #   type: js
 # - url: !resource card-modder/card-modder.js
 #   type: js
 # - url: https://unpkg.com/moment@2.22.2/moment.js
 #   type: js
 # - url: !resource calendar/calendar-card.js
 #   type: module
 # - url: !resource dual-gauge/dual-gauge-card.js
 #   type: js
 # - url: !resource kiosk/kiosk.js
 #   type: js
 # - url: !resource button-card/button-card.js
 #   type: module

 # - url: !resource useful-markdown-card/useful-markdown-card.js
 #   type: js
 # - url: !resource column-card/column-card.js
 #   type: js
 # - url: !resource tracker-card/tracker-card.js?v=1.2.3
 #   type: js
 # - url: !resource light-slider/light-slider-element.js
 #   type: js
 # - url: !resource state-element/state-element.js
 #   type: js
 # - url: !resource username-element/username-element.js
 #   type: js
 # - url: !resource state-attribute-element/state-attribute-element.js
 #   type: js
 # - url: !resource mini-media-player/mini-media-player.js?v=0.5
 #   type: module
 # - url: !resource toggle-lock-entity-row/toggle-lock-entity-row.js
 #   type: js

  # custom-lovelace
  - url: /customcards/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js
    type: js  
  - url: /customcards/custom-lovelace/beer-card/beer-card.js
    type: js  
  - url: /customcards/custom-lovelace/bignumber-card/bignumber-card.js
    type: js  
  - url: /customcards/custom-lovelace/entity-attributes-card/entity-attributes-card.js
    type: js  
  - url: /customcards/custom-lovelace/gauge-card/gauge-card.js
    type: js  
  - url: /customcards/custom-lovelace/group-card/group-card.js
    type: js  
  - url: /customcards/custom-lovelace/home-setter/home-setter.js
    type: js  
  - url: /customcards/custom-lovelace/monster-card/monster-card.js
    type: js  
  - url: /customcards/custom-lovelace/plan-coordinates/plan-coordinates.js
    type: js  
  - url: /customcards/custom-lovelace/thermostat-card/thermostat-card.js
    type: js 
  # tracker-card 
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  # other
  - url: /local/card-tools.js
    type: js
  - url: /local/pollenkoll-card.js
    type: js
  - url: /customcards/text-element.js
    type: js
  - url: /customcards/circle-sensor-card.js
    type: module
  - url: /customcards/vertical-stack-in-card.js
    type: js
  - url: /customcards/krisinfo-card.js
    type: js
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /customcards/slider-entity-row.js
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css 
    
title: Home
# excluded_entities:
#   {% for state in states.alert %}
#   - {{ states.alert[state].entity_id }}
#   {% endfor %}
#   {% for state in states.automation %}
#   - {{ states.automation[state].entity_id }}
#   {% endfor %}
#   {% for state in states.zwave %}
#   - {{ states.zwave[state].entity_id }}
#   {% endfor %}
views:
  - !include 00_home_view.yaml
  - !include 10_downstairs_view.yaml
  - !include 20_upstairs_view.yaml
  - !include 30_basement_view.yaml
  - !include 40_car_view.yaml
  - !include 50_finance_view.yaml
  - !include 60_pool_view.yaml
  - !include 99_system_view.yaml
