- id: '1532956645522'
  alias: Lights on - just before sunset
  initial_state: on
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - before: '23:30'
    condition: time
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_on
  - data:
      entity_id: light.hallway_upstairs
    service: light.turn_on
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch
    service: switch.turn_on
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch_2
    service: switch.turn_on
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch_3
    service: switch.turn_on
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch_4
    service: switch.turn_on
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch
    service: switch.turn_on
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch_2
    service: switch.turn_on
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch_3
    service: switch.turn_on
  - data:
      entity_id: switch.timer
    service: switch.turn_on

- id: '1534049443061'
  alias: Lights off - by midnight
  initial_state: on
  trigger:
  - at: '23:59'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
  - data:
      entity_id: light.hallway_upstairs
    service: light.turn_off
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch
    service: switch.turn_off
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch_2
    service: switch.turn_off
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch_3
    service: switch.turn_off
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch_4
    service: switch.turn_off
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch
    service: switch.turn_off
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch_2
    service: switch.turn_off
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch_3
    service: switch.turn_off
  - data:
      entity_id: switch.timer
    service: switch.turn_off

- id: '1543169877134'
  alias: Lights on - in the morning
  initial_state: on
  trigger:
  - at: 06:00
    platform: time
  condition:
  - before: sunrise
    condition: sun
  action:
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch
    service: switch.turn_on
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch
    service: switch.turn_on
  - data:
      entity_id: switch.timer
    service: switch.turn_on
  - data:
      entity_id: light.hallway_upstairs
    service: light.turn_on

- id: '1543170136376'
  alias: Lights off - by sunrise
  initial_state: on
  trigger:
  - event: sunrise
    offset: 00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.nodon_msp31xx_micro_smart_plug_switch
    service: switch.turn_off
  - data:
      entity_id: switch.everspring_an180_plugin_onoff_module_switch
    service: switch.turn_off
  - data:
      entity_id: switch.timer
    service: switch.turn_off
  - data:
      entity_id: light.hallway_upstairs
    service: light.turn_off

- id: '1546120746337'
  alias: Run Backup 3AM
  initial_state: on
  trigger:
  - at: 03:00
    platform: time
  condition: []
  action:
  - alias: ''
    data: {}
    service: script.ha_backup

- id: '1546532215998'
  alias: Set Theme by daylight
  initial_state: on
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  condition: []
  action:
  - service: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
            {{ "light-lightred"}}
        {% else %}  
            {{ "dark-lightred"}}
        {% endif %}


#- alias: 'Hass start'
#  trigger:
#    platform: homeassistant
#    event: start
#    action: 
#      - service: automation.turn_on
#        entity_id: groups.all_automations