homeassistant:
  name: Home                                        # Name of the location where Home Assistant is running
  latitude: !secret lat_coord                       # Location required to calculate the time the sun rises and sets
  longitude: !secret long_coord
  elevation: 230                                    # Impacts weather/sunrise data (altitude above sea level in meters)
  unit_system: metric                               # metric for Metric, imperial for Imperial
  time_zone: !secret time_zone                      # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.72.0/24 
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: true
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config/www'
  # internal_url: !secret internal_url
  # external_url: !secret external_url

config:                                             # Enables configuration UI
hassio:
http:
  use_x_forwarded_for: true
  trusted_proxies:
  #  - 172.30.33.0/24
    - 127.0.0.1
    - ::1
  #base_url: !secret base_url
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem


#updater:
#  include_used_components: true
  
conversation:                                       # Allows you to issue voice commands from the frontend in enabled browsers
#customizer:
#  custom_ui: hosted
#cloud: !include assistants/cloud.yaml
#homekit: !include assistants/homekit.yaml
#ios: !include notify/ios_config.yaml

#discovery:                                          # Discover some devices automatically

#hacs:
#  token: !secret hacs_token
#  appdaemon: true

# ########################################
# ###                GUI               ###
# ########################################

map:                                                # Enables a map showing the location of tracked devices
frontend:                                           # Enables the frontend
  javascript_version: auto 
  themes: !include_dir_merge_named themes
  #themes: !include_dir_named themes
    # Denna är snygg: Stell Blue with Colors

lovelace_gen:

lovelace:
  mode: yaml

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

system_health:

#uilogs:


# ########################################
# ###              LOGGING             ###
# ########################################
recorder: !include logging/recorder.yaml             # Enables support for tracking state changes over time
history: !include logging/history.yaml              
#logbook: !include logging/logbook.yaml              # View all events in a logbook
#logger: !include logging/logger.yaml


# ########################################
# ###               HUBS               ###
# ########################################

# zwave:
#     usb_path: /dev/ttyACM0

#maxcube:
#  gateways:
#    - host: !secret maxcube_ip

hue:
  bridges:
    - host: !secret huebridge_ip
      #allow_unreachable: true
      #allow_hue_groups: true
      
shelly:

tuya:
  username: !secret tuya_usr
  password: !secret tuya_pwd
  country_code: !secret tuya_country_code


# ########################################
# ###              ENTITIES            ###
# ########################################

verisure:
  username: !secret verisure_username
  password: !secret verisure_password

media_player: !include entities/media_player.yaml
bmw_connected_drive: !include entities/bmw.yaml 

camera: !include entities/camera.yaml

#device_tracker: !include entities/device_tracker.yaml
zone: !include zone.yaml

home_connect:
  client_id: !secret homeconnect_client_id 
  client_secret: !secret homeconnect_client_secret

spotify:
  client_id: !secret spotify_client_id 
  client_secret: !secret spotify_client_secret  

spotcast:
  sp_dc: !secret sp_dc 
  sp_key: !secret sp_key    

# ########################################
# ###             SERVICES             ###
# ########################################

sun:                                                # Track the sun
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

binary_sensor: !include entities/binary_sensors.yaml

notify: !include notify/notify.yaml
python_script:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-raspi
  keepalive: 60
  username: !secret mqtt_username 
  password: !secret mqtt_password 
  discovery: true
  discovery_prefix: homeassistant

ifttt:
  key: !secret ifttt_api_key

alexa:

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

#tts:
#  - platform: google                                # Text to speech

#shell_command:
  #lovelace_gen: 'python /config/lovelace-gen.py > /config/lovelace-gen.log'
  #lovelace_gen_states: !secret lovelace_gen_states

mobile_app:

input_boolean:
  go_to_bed:
    name: Indicates gone to bed
    icon: mdi:sleep



# ########################################
# ###      SCRIPTS & AUTOMATIONS       ###
# ########################################

script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
group: !include groups.yaml