homeassistant:
  name: Home                                        # Name of the location where Home Assistant is running
  latitude: !secret lat_coord                       # Location required to calculate the time the sun rises and sets
  longitude: !secret long_coord
  elevation: 151                                    # Impacts weather/sunrise data (altitude above sea level in meters)
  unit_system: metric                               # metric for Metric, imperial for Imperial
  time_zone: !secret time_zone                      # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config/www'
config:                                             # Enables configuration UI
hassio:
http:
  api_password: !secret http_password               # Secrets are defined in the file secrets.yaml
  base_url: !secret base_url
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  #trusted_networks: 
  #  - !secret ip_trusted_network
updater:
conversation:                                       # Allows you to issue voice commands from the frontend in enabled browsers
#customizer:
#  custom_ui: hosted
cloud: !include assistants/cloud.yaml
#homekit: !include assistants/homekit.yaml
#ios: !include notify/ios_config.yaml

#discovery:                                          # Discover some devices automatically


# ########################################
# ###                GUI               ###
# ########################################
map:                                                # Enables a map showing the location of tracked devices
frontend:                                           # Enables the frontend
  javascript_version: auto 
  themes: !include_dir_named themes

lovelace:
  mode: yaml

panel_iframe:
  configurator:
    title: Editor
    icon: mdi:wrench
    url: !secret url_configurator
  #sqlite:
  #  title: SQLite Web
  #  icon: mdi:database
  #  url: !secret url_sqlite
  log_viewer:
    title: Log
    icon: mdi:information-outline
    url: !secret url_logviewer
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret url_terminal

custom_updater:
  mode: storage
  show_installable: true
  track:
    - cards
    - components
  card_urls:
    #- https://raw.githubusercontent.com/custom-cards/text-element/master/text-element.js
    #- https://raw.githubusercontent.com/custom-cards/vertical-stack-in-card/master/vertical-stack-in-card.js
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json

system_health:


# ########################################
# ###              LOGGING             ###
# ########################################
recorder: !include logging/recorder.yaml
history: !include logging/history.yaml              # Enables support for tracking state changes over time
logbook: !include logging/logbook.yaml              # View all events in a logbook
logger: !include logging/logger.yaml


# ########################################
# ###               HUBS               ###
# ########################################

zwave:
    usb_path: /dev/ttyACM0

maxcube:
  gateways:
    - host: !secret maxcube_ip

hue:
  bridges:
    - host: !secret huebridge_ip
      #allow_unreachable: true
      #allow_hue_groups: true


# ########################################
# ###              ENTITIES            ###
# ########################################

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  

media_player: !include entities/media_player.yaml
bmw_connected_drive: !include entities/bmw.yaml 

camera:
  platform: mjpeg
  mjpeg_url: !secret dlink_camera_url

device_tracker: !include entities/device_tracker.yaml
zone: !include zone.yaml


# ########################################
# ###             SERVICES             ###
# ########################################

sun:                                                # Track the sun
notify: !include notify/notify.yaml
python_script:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-raspi
  keepalive: 60
  username: !secret mqtt_username 
  password: !secret mqtt_password 
  discovery: true

ifttt:
  key: !secret ifttt_api_key

#google:
  #client_id: !secret google_id
  #client_secret: !secret google_secret

#tts:
#  - platform: google                                # Text to speech

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py > /config/lovelace-gen.log'
  #lovelace_gen_states: !secret lovelace_gen_states
  

# ########################################
# ###      SCRIPTS & AUTOMATIONS       ###
# ########################################

script: !include scripts.yaml
automation: !include automations.yaml
