homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 60.481591
  longitude: 15.443260 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 151
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

themes: !include themes.yaml
    
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  # base_url: https://heltal.eu:8123
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  include:
    domains:
      -sensor
      -switch
      -media_player

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml

zwave:
    usb_path: /dev/ttyACM0
    
maxcube:
  gateways:
    - host: 192.168.72.243

bmw_connected_drive:
  name:
    username: pjalzen
    password: !secret bmw_password
    region: rest_of_world
    
verisure:
  username: perjohan.alzen@gmail.com
  password: !secret verisure_password
  
media_player:
   platform: heos
   host: 192.168.72.62
   name: heos_altan

camera:
  platform: mjpeg
  mjpeg_url: http://192.168.72.150/video/mjpg.cgi