- platform: template
  sensors:
    motion_poolarea:
      friendly_name: Camera Pool Area
      device_class: motion
      entity_id: camera.reolink_pool_area
      value_template: "{{ is_state('camera.reolink_pool_area', 'motion') }}"
      delay_off: 
        seconds: 5

- platform: template
  sensors:
    motion_garage:
      friendly_name: Camera Front Door
      device_class: motion
      entity_id: camera.reolink_garage
      value_template: "{{ is_state('camera.reolink_garage', 'motion') }}"
      delay_off: 
        seconds: 5
