- platform: generic
  still_image_url: !secret dlink_camera_url
- platform: mjpeg
  mjpeg_url: http://192.168.72.135/mjpeg



- platform: reolink_dev
  host: !secret reolink_pool_ip
  username: !secret reolink_pool_username
  password: !secret reolink_pool_password
  name: Reolink Pool Area
  # stream: main or sub (optional, default main)
  # protocol: rtmp or rtsp (optional, default rtmp)
  # channel: NVR camera channel (optional, default 0)
  # scan_interval: 5 (optional, default 30s)

- platform: template
  switches:
    camera_poolarea_email:
      value_template: "{{ is_state_attr('camera.reolink_pool_area', 'email_enabled', true) }}"
      turn_on:
        service: camera.enable_email
        data:
          entity_id: camera.reolink_pool_area
      turn_off:
        service: camera.disable_email
        data:
          entity_id: camera.reolink_pool_area
      icon_template: >-
        {% if is_state_attr('camera.reolink_pool_area', 'email_enabled', true) %}
          mdi:email
        {% else %}
          mdi:email-outline
        {% endif %}
          
    camera_poolarea_ftp:
      value_template: "{{ is_state_attr('camera.reolink_pool_area', 'ftp_enabled', true) }}"
      turn_on:
        service: camera.enable_ftp
        data:
          entity_id: camera.reolink_pool_area
      turn_off:
        service: camera.disable_ftp
        data:
          entity_id: camera.reolink_pool_area
      icon_template: >-
        {% if is_state_attr('camera.reolink_pool_area', 'ftp_enabled', true) %}
          mdi:filmstrip
        {% else %}
          mdi:filmstrip-off
        {% endif %}
        
    camera_poolarea_ir_lights:
      value_template: "{{ is_state_attr('camera.reolink_pool_area', 'ir_lights_enabled', true) }}"
      turn_on:
        service: camera.enable_ir_lights
        data:
          entity_id: camera.reolink_pool_area
      turn_off:
        service: camera.disable_ir_lights
        data:
          entity_id: camera.reolink_pool_area
      icon_template: >-
        {% if is_state_attr('camera.reolink_pool_area', 'ir_lights_enabled', true) %}
          mdi:flashlight
        {% else %}
          mdi:flashlight-off
        {% endif %}