- platform: nmap_tracker
  hosts: !secret nmap_tracker_hosts
  home_interval: 10
  track_new_devices: true
  exclude:
    - !secret hassio_ip

#- platform: owntracks
    #mqtt_topic: "owntracks/#"
      
- platform: mqtt
  devices:
    perjohan_pj_iphone: 'owntracks/perjohan/pj iphone'

#- platform: asuswrt
#    host: 192.168.72.1
#    username: !secret lyra_username
#    password: !secret lyra_password