 #   track_new_devices: True
 #   interval_seconds: 20
 #   consider_home: 360
 #   home_interval: 10
 #   exclude:
 #     - !secret hass_host_ip
  # - platform: bluetooth_tracker
  #   track_new_devices: false
  # - platform: owntracks
 # - platform: tile
 #   username: !secret tile_username
 #   password: !secret tile_password

# ############################################################

- platform: nmap_tracker
  hosts: !secret nmap_tracker_hosts
  home_interval: 10
  
#- platform: owntracks
    #mqtt_topic: "owntracks/#"
      
- platform: mqtt
  devices:
    perjohan_pj_iphone: 'owntracks/perjohan/pj iphone'

#- platform: asuswrt
#    host: 192.168.72.1
#    username: !secret lyra_username
#    password: !secret lyra_password