esphome:
  name: sensor_node_test
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Sveas rike"
  password: "Erik2001"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Node Test"
    password: "k5T3s4PK5EpZ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
