withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_consumer_secret
  profiles:
    - PER

strava:
    client_id: !secret strava_client_id
    client_secret: !secret strava_client_secret

# Sensors
sensor:
  - platform: strava
    athlete: me
    fields:
      - follower_count
      - friend_count
      - weight
    # Check stravalib for full list of supported fields:
    # https://pythonhosted.org/stravalib/api.html#stravalib.model.AthleteStats
    stats:
      # Other activity totals:
      # - recent_ride_totals
      # - ytd_ride_totals
      # - ytd_run_totals
      # - all_ride_totals
      # - all_ride_totals
      - biggest_ride_distance
      - biggest_climb_elevation_gain
      - recent_run_totals.achievement_count
      - recent_run_totals.count
      - recent_run_totals.distance
      - recent_run_totals.elapsed_time
      - recent_run_totals.elevation_gain
      - recent_run_totals.moving_time

    # https://pythonhosted.org/stravalib/api.html#stravalib.model.Activity
    last_activity:
      - distance
      - moving_time
      - elapsed_time
      - total_elevation_gain
      - type
      - achievement_count
      - pr_count
      - kudos_count
      - comment_count
      - athlete_count
      - total_photo_count
      - commute
      - manual
      - private
      - flagged
      - average_speed
      - max_speed
      - device_watts
      - has_kudoed
      - average_watts
      - max_watts
      - suffer_score
      - average_heartrate
      - max_heartrate
      - average_cadence
      - kilojoules
      - device_name
      - calories
      - workout_type

  # Check stravalib for full list of supported fields:
  # https://pythonhosted.org/stravalib/api.html#stravalib.model.Shoe
  - platform: strava
    shoe: 4403312
    fields:
      - name
      - distance
      - primary
      - brand_name
      - model_name
      - description

  # Check stravalib for full list of supported fields:
  # https://pythonhosted.org/stravalib/api.html#stravalib.model.Bike
  - platform: strava
    bike: 5683777
    fields:
      - name
      - distance
      - primary
      - brand_name
      - model_name
      - frame_type

  # Check stravalib for full list of supported fields:
  # https://pythonhosted.org/stravalib/api.html#stravalib.model.Club
  - platform: strava
    club: 483278
    fields:
      - name
      - description
      - club_type
      - sport_type
      - city
      - state
      - country
      - private
      - member_count
      - url