sensor:
  - platform: pollenniva
    scan_interval: 4        #(default, optional)
    state_as_string: false  #(default, optional, show states as strings as per STATES above)
    sensors:
      - city: Borlänge
        days_to_track: 3 (0-3, optional)
        allergens:
          - Al
          - Alm
          - Asp
          - Björk
          - Ek
          - Gråbo
          - Gräs
          - Hassel
          - Sälg
          
