sensor:
  - platform: template
    sensors:
      shelly_plug_s_has_firmware_update:
        friendly_name: "Shelly Plug S Firmware Update"
        entity_id: sensor.shelly_plug_s_has_firmware_update
        value_template: "{{ state_attr('sensor.shelly_shplg_s_b86d7c_current_consumption', 'has_firmware_update') }}"

  - platform: template
    sensors:
      shelly_1_has_firmware_update:
        friendly_name: "Shelly 1 Firmware Update"
        entity_id: sensor.shelly_1_has_firmware_update
        value_template: "{{ state_attr('sensor.shelly_shsw_1_942187', 'has_firmware_update') }}"