sensor:
  - platform: alpha_vantage
    api_key: !secret alpha_vantage_api_key
    symbols:
      - symbol: AMZN
        name: Amazon
      - symbol: MSFT
        name: Microsoft
      - symbol: NKE
        name: Nike
    #foreign_exchange:
    #  - name: USD_EUR
    #    from: USD
    #    to: EUR
    #  - name: EUR_SEK
    #    from: EUR
    #    to: SEK

#  - platform: yahoo_finance
#    name: Amazon
#    symbol: AWS

#  - platform: yahoo_finance
#    name: Microsoft
#    symbol: MSFT