# *********************************
# Stock sensors
# -------------
# Boliden
# Ericsson
# Amazon
# Volvo
# Microsoft
# Husqvarna
# Starbucks
# Salesforce
# Capgemini
# Sandvik
# SSAB
# Stora Enso
# Jumia Technologies
# Toadman Interactive
# *********************************

sensor:
  - platform: avanza_stock
    stock: 19002
    name: OMX Stockholm 30
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 18985
    name: Dow Jones
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 811105
    name: Toadman Interactive
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 3986
    name: Amazon
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 745885
    name: Capgemini
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 5471
    name: Sandvik
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 3873
    name: Microsoft
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 45189
    name: Husqvarna
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 952055
    name: Jumia Technologies
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 5422
    name: Stora Enso
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 5269
    name: Volvo
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 5240
    name: Ericsson
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 5564
    name: Boliden
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 5261
    name: SSAB
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 194763
    name: Salesforce
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
  - platform: avanza_stock
    stock: 4456
    name: Starbucks
    monitored_conditions:
      #change
      #changePercent
      #name
      - highestPrice
      - tickerSymbol
      - totalValueTraded
      - totalVolumeTraded
      - priceAtStartOfYear
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo



#  - platform: alpha_vantage
#    api_key: !secret alpha_vantage_api_key
#    symbols:
#      - symbol: AMZN
#        name: Amazon
#      - symbol: MSFT
#        name: Microsoft
#      - symbol: NKE
#        name: Nike
    #foreign_exchange:
    #  - name: USD_EUR
    #    from: USD
    #    to: EUR
    #  - name: EUR_SEK
    #    from: EUR
    #    to: SEK

#  - platform: yahoo_finance
#    name: Amazon
#    symbol: AWS

#  - platform: yahoo_finance
#    name: Microsoft
#    symbol: MSFT