sensor:
  - platform: alpha_vantage
    api_key: DY5DNO61YP2GA1SM
    symbols:
      - symbol: AMZN
        name: Amazon
      - symbol: MSFT
        name: Micorsoft
      - symbol: MSFT
        name: Micorsoft
      - symbol: NKE
        name: Nike
      - symbol: BOL.ST
        name: Boliden
    foreign_exchange:
      - name: USD_EUR
        from: USD
        to: EUR
      - name: EUR_SEK
        from: EUR
        to: SEK

#  - platform: yahoo_finance
#    name: Amazon
#    symbol: AWS

#  - platform: yahoo_finance
#    name: Microsoft
#    symbol: MSFT