############################################################
##    Sensor Config for Next Sunrise Time Reformatting    ##
############################################################

- platform: template
  sensors: 
    nextsunrise:
      friendly_name: "Next Sun Rise"
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%-H:%M') }}"
      icon_template: mdi:weather-sunset-up

    nextsunset:
      friendly_name: "Next Sun Set"
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%-H:%M') }}"
      icon_template: mdi:weather-sunset-down
