sensor:
  - platform: yahoofinance
    show_trending_icon: true
    scan_interval:
      hours: 4
    symbols:
      - ^GSPC
      - ^GDAXI
      - ^OMX
      - ^N225
      - ^FTSE
      - ^DJI
      - ^IXIC
      - EURUSD=X
      - EURSEK=X
      - SEK=X
      - EURGBP=X

